services:
  database:
    container_name: "syncroad_database"
    hostname: database
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/postgres.env
    ports:
      - "5432:5432"
    networks:
      - appnet 
    command: [ "postgres", "-c", "log_statement=all" ] # Debugging

  backend:
    container_name: "syncroad_backend"
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
  
    # Terminal
    stdin_open: true
    tty: true 
    depends_on:
      - database
    ports:
      - "8000:8000"
      - "5005:5005/udp"   

    networks:
      - appnet  
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: "syncroad_frontend"
    restart: "unless-stopped"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents overwriting 
    ports:
      - "8081:8081" # Metro Bundler -> React Native Expo
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

    networks:
      - appnet  # Attach to the custom network

volumes:
  postgres_data:

networks:
  appnet:
    name: syncroad_network 