services:
  database:
    container_name: "syncroad-database"
    hostname: database
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/postgres.env
    ports:
      - "5432:5432"
    networks:
      - appnet  # Attach to the custom network
    command: [ "postgres", "-c", "log_statement=all" ] # Debugging


  backend:
    container_name: "syncroad_backend"
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    # env_file:
    #   - ./backend/.env # Uncomment if you have a .env file, maybe later for api keys
    # Terminal
    stdin_open: true 
    tty: true 
    depends_on:
      - database
    ports:
      - "8000:8000"
    networks:
      - appnet  # Attach to the custom network
    command: python -u api/manage.py runserver 0.0.0.0:8000


  frontend:
    container_name: "syncroad_frontend"
    restart: "unless-stopped"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents overwriting node_modules
    ports:
      - "8081:8081" # Metro Bundler port
    networks:
      - appnet  # Attach to the custom network

volumes:
  postgres_data:

networks:
  appnet:
    name: syncroad-network 