name: Code Quality Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Linters & Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Python Formatting with Black
      - name: Install Black
        run: pip install black

      - name: Check Python Formatting
        run: black --check .

      # JavaScript Formatting with Prettier
      - name: Install Prettier
        run: npm install -g prettier

      - name: Check JS Formatting
        run: prettier --check "**/*.{js,jsx,ts,tsx}"
